### ISSUE TITLE
Can't create new nodes

### ISSUE THREAD

**Issue by theSoenke** [modopotato/LibnoiseDesigner#1]
Hi,

this libnoise designer looks like an really interesting project, but unfortunately i have a few issues. First the AssemblyInfo.cs for the NetworkUI solution seems to be missing and i had to generate it. 
Now my problem is when i start the application and create a new node nothing happens. I just cloned the project and the only thing i changed is the AssemlyInfo.cs

Maybe an idea whats wrong?

Thanks

**Comment by dhlevi** [comment]
@theSoenke I'm sure you've long since forgotten about this, but anyway, seemed to be an issue with Namespaces on the main component. I've updated the build recently and this doesn't appear to be an issue anymore!
